### ISSUE TITLE
[0,5pt] Set up the project with Webpack and Jest- group task

### ISSUE THREAD

**Issue by VTY1999** [VTY1999/JS-Group-capstone#2]
- Set up Gitflow
- Set up webpack
- Set up a JavaScript testing library (Jest)
- The team consists of 2 people.

[Link to the project](https://github.com/VTY1999/JS-Group-capstone/projects/2)

**Comment by od-c0d3r** [comment]
Asslam Alikom Team, @VTY1999 @SirriRyisa 

Hi 👋🏽, 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the link to the issue which contain information about your canban board as per requested by the project requirements, [LINK](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/setup_kanban_board.md#:~:text=Open%20a%20new%20issue%20in%20your%20repository)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by brytebee** [comment]
Hi, @VTY1999 @SirriRyisa 👋, 

## Highlights

Good job so far!
- successfully created a GitHub Project with Kanban Template✔️
- copied some cards with the script ✔️ 
- assigned some tasks to group members✔️


There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

- [ ] **Required:** All tasks(cards) must be assigned to a team member. 

![image](https://user-images.githubusercontent.com/27709832/153873072-a7aa3598-8142-4ed2-81d9-4936e9296336.png)

- [ ] **Required:** The cards for a group of two team members should be 15. Kindly add the remaining 2 cards. 

![image](https://user-images.githubusercontent.com/27709832/153873702-9c25b250-8af0-4122-aa7c-ef481d959897.png)

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Mihndim2020** [comment]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi Team, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
